# Generated by Django 4.1.1 on 2022-10-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_shippingaddress_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='surname',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
