# Generated by Django 4.1.1 on 2022-09-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Kliknij powyżej by przeczytać post.', max_length=50),
        ),
    ]
